# Generated by Django 4.0.1 on 2022-03-18 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Soen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualSpotMo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AsName', models.CharField(default=' 現場', max_length=20, verbose_name='現場名')),
                ('AsCompany', models.CharField(blank=True, default='株式会社', max_length=60, null=True, verbose_name='元請会社名')),
                ('AsManager', models.CharField(blank=True, default=' 所長', max_length=60, null=True, verbose_name='現場所長名')),
                ('AsPostcode', models.CharField(blank=True, default='857-', max_length=60, null=True, verbose_name='郵便番号')),
                ('AsAddress', models.CharField(blank=True, default='佐世保市', max_length=60, null=True, verbose_name='現場住所')),
                ('Astel', models.CharField(blank=True, default='0956-', max_length=15, null=True, verbose_name='電話番号')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsSoenMo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConstractionDetails', models.CharField(default='金属･内装工事', max_length=50, verbose_name='工事内容')),
                ('ContractDate', models.DateField(blank=True, default='2022-04-01', null=True, verbose_name='契約日')),
                ('StartDate', models.DateField(blank=True, default='2022-04-01', null=True, verbose_name='工期開始日')),
                ('EndDate', models.DateField(blank=True, default='2023-03-31', null=True, verbose_name='工期終了日')),
                ('AsSManager', models.ManyToManyField(blank=True, default='-', related_name='soenmanager', to='Soen.MemberMo')),
                ('AsSMember', models.ManyToManyField(blank=True, default='-', related_name='soenmember', to='Soen.MemberMo')),
                ('actualspot', models.OneToOneField(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='actualspot', to='Show.actualspotmo')),
            ],
        ),
    ]
