# Generated by Django 4.0.1 on 2022-02-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assoenm',
            name='ContractDate',
            field=models.DateField(verbose_name='契約日0000-00-00'),
        ),
    ]
