# Generated by Django 4.0.1 on 2022-03-01 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0002_alter_blogm_text_alter_blogm_title_and_more'),
        ('Show', '0002_alter_assoenm_contractdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assoenm',
            name='AsSManager',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='soenmanager', to='Soen.memberm'),
        ),
        migrations.AlterField(
            model_name='assoenm',
            name='ContractDate',
            field=models.DateField(default='0000-00-00', verbose_name='契約日'),
        ),
        migrations.AlterField(
            model_name='assoenm',
            name='actualspot',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='actualspot', to='Show.actualspotm'),
        ),
    ]
