# Generated by Django 4.0.1 on 2022-03-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0002_alter_blogm_text_alter_blogm_title_and_more'),
        ('Show', '0003_alter_assoenm_assmanager_alter_assoenm_contractdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assoenm',
            name='AsSMember',
            field=models.ManyToManyField(default='-', related_name='soenmember', to='Soen.MemberM'),
        ),
    ]
