# Generated by Django 4.0.1 on 2022-03-01 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0004_alter_assoenm_assmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assoenm',
            name='actualspot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualspot', to='Show.actualspotm'),
        ),
    ]
