# Generated by Django 4.0.1 on 2022-03-01 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0002_alter_blogm_text_alter_blogm_title_and_more'),
        ('Show', '0005_alter_assoenm_actualspot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assoenm',
            name='actualspot',
        ),
        migrations.AddField(
            model_name='actualspotm',
            name='AsSoen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoenm', to='Show.assoenm'),
        ),
        migrations.AlterField(
            model_name='assoenm',
            name='AsSManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soenmanager', to='Soen.memberm'),
        ),
        migrations.AlterField(
            model_name='assoenm',
            name='AsSMember',
            field=models.ManyToManyField(blank=True, null=True, related_name='soenmember', to='Soen.MemberM'),
        ),
    ]
