# Generated by Django 4.0.1 on 2022-03-02 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0002_alter_blogm_text_alter_blogm_title_and_more'),
        ('Show', '0006_remove_assoenm_actualspot_actualspotm_assoen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualspotm',
            name='AsSoen',
        ),
        migrations.AddField(
            model_name='assoenm',
            name='actualspot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actualspot', to='Show.actualspotm'),
        ),
        migrations.RemoveField(
            model_name='assoenm',
            name='AsSManager',
        ),
        migrations.AddField(
            model_name='assoenm',
            name='AsSManager',
            field=models.ManyToManyField(default='-', related_name='soenmanager', to='Soen.MemberM'),
        ),
        migrations.AlterField(
            model_name='assoenm',
            name='AsSMember',
            field=models.ManyToManyField(default='-', related_name='soenmember', to='Soen.MemberM'),
        ),
    ]
