# Generated by Django 4.0.1 on 2022-03-02 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0007_remove_actualspotm_assoen_assoenm_actualspot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assoenm',
            name='actualspot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actualspot', to='Show.actualspotm'),
        ),
    ]
