# Generated by Django 4.0.1 on 2022-03-02 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0008_alter_assoenm_actualspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assoenm',
            name='actualspot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actualspot', to='Show.actualspotm'),
        ),
    ]
