# Generated by Django 4.0.1 on 2022-03-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0009_alter_assoenm_actualspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assoenm',
            name='actualspot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actualspot', to='Show.actualspotm'),
        ),
    ]
