# Generated by Django 4.0.1 on 2022-03-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0002_alter_blogm_text_alter_blogm_title_and_more'),
        ('Show', '0011_alter_assoenm_actualspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assoenm',
            name='AsSManager',
            field=models.ManyToManyField(blank=True, null=True, related_name='soenmanager', to='Soen.MemberM'),
        ),
        migrations.AlterField(
            model_name='assoenm',
            name='AsSMember',
            field=models.ManyToManyField(blank=True, null=True, related_name='soenmember', to='Soen.MemberM'),
        ),
        migrations.AlterField(
            model_name='assoenm',
            name='ContractDate',
            field=models.DateField(blank=True, null=True, verbose_name='契約日'),
        ),
        migrations.AlterField(
            model_name='assoenm',
            name='EndDate',
            field=models.DateField(blank=True, null=True, verbose_name='工期終了日'),
        ),
        migrations.AlterField(
            model_name='assoenm',
            name='StartDate',
            field=models.DateField(blank=True, null=True, verbose_name='工期開始日'),
        ),
        migrations.AlterField(
            model_name='assoenm',
            name='actualspot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actualspot', to='Show.actualspotm'),
        ),
    ]
