# Generated by Django 3.2.7 on 2021-11-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soenmodel',
            name='file10',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Link10'),
        ),
    ]
