# Generated by Django 3.2.7 on 2021-11-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimex', '0002_alter_soenmodel_file10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencemodel',
            name='name',
            field=models.CharField(blank=True, choices=[('-', '-'), ('1級建築士', '1級建築士'), ('2級建築士', '2級建築士'), ('1級建築施工管理技士', '1級建築施工管理技士'), ('2級建築施工管理技士（建築）', '2級建築施工管理技士（建築）'), ('2級建築施工管理技士（仕上げ）', '2級建築施工管理技士（仕上げ）'), ('1級技能士\u3000内装仕上げ施工（鋼製下地工事作業）', '1級技能士\u3000内装仕上げ施工（鋼製下地工事作業）'), ('2級技能士\u3000内装仕上げ施工（鋼製下地工事作業）', '2級技能士\u3000内装仕上げ施工（鋼製下地工事作業）'), ('1級技能士\u3000内装仕上げ施工（ﾎﾞｰﾄﾞ仕上げ工事作業）', '1級技能士\u3000内装仕上げ施工（ﾎﾞｰﾄﾞ仕上げ工事作業）'), ('2級技能士\u3000内装仕上げ施工（ﾎﾞｰﾄﾞ仕上げ工事作業）', '2級技能士\u3000内装仕上げ施工（ﾎﾞｰﾄﾞ仕上げ工事作業）'), ('1級技能士\u3000内装仕上げ施工（ﾌﾟﾗｽﾁｯｸ系床仕上げ工事作業）', '1級技能士\u3000内装仕上げ施工（ﾌﾟﾗｽﾁｯｸ系床仕上げ工事作業）'), ('2級技能士\u3000内装仕上げ施工（ﾌﾟﾗｽﾁｯｸ系床仕上げ工事作業）', '2級技能士\u3000内装仕上げ施工（ﾌﾟﾗｽﾁｯｸ系床仕上げ工事作業）'), ('1級技能士\u3000内装仕上げ施工（ｶｰﾍﾟｯﾄ系床仕上げ工事作業）', '1級技能士\u3000内装仕上げ施工（ｶｰﾍﾟｯﾄ系床仕上げ工事作業）'), ('2級技能士\u3000内装仕上げ施工（ｶｰﾍﾟｯﾄ系床仕上げ工事作業）', '2級技能士\u3000内装仕上げ施工（ｶｰﾍﾟｯﾄ系床仕上げ工事作業）'), ('1級技能士\u3000表装（表具作業）', '1級技能士\u3000表装（表具作業）'), ('2級技能士\u3000表装（表具作業）', '2級技能士\u3000表装（表具作業）'), ('1級技能士', '1級技能士'), ('2級技能士', '2級技能士'), ('3級技能士', '3級技能士'), ('自動車運転免許', '自動車運転免許'), ('免許20', '免許20')], max_length=40, null=True, verbose_name='免許'),
        ),
        migrations.AlterField(
            model_name='skilltraningmodel',
            name='name',
            field=models.CharField(blank=True, choices=[('-', '-'), ('有機溶剤作業主任者', '有機溶剤作業主任者'), ('玉掛け技能講習', '玉掛け技能講習'), ('特定化学物質等作業主任者', '特定化学物質等作業主任者'), ('小型移動式クレン運転技能講習', '小型移動式クレン運転技能講習'), ('高所作業車運転技能講習', '高所作業車運転技能講習'), ('技能講習6', '技能講習6'), ('技能講習7', '技能講習7'), ('技能講習8', '技能講習8'), ('技能講習9', '技能講習9'), ('技能講習10', '技能講習10'), ('技能講習11', '技能講習11'), ('技能講習12', '技能講習12'), ('技能講習13', '技能講習13'), ('技能講習14', '技能講習14'), ('技能講習15', '技能講習15'), ('技能講習16', '技能講習16'), ('技能講習17', '技能講習17'), ('技能講習18', '技能講習18'), ('技能講習19', '技能講習19'), ('技能講習20', '技能講習20')], max_length=30, null=True, verbose_name='技能講習'),
        ),
        migrations.AlterField(
            model_name='soenmodel',
            name='employmentinsurance',
            field=models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '適用除外'), ('4', '-')], max_length=100, null=True, verbose_name='雇用保険'),
        ),
        migrations.AlterField(
            model_name='soenmodel',
            name='file10',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Link10'),
        ),
        migrations.AlterField(
            model_name='soenmodel',
            name='healthInsurance',
            field=models.CharField(blank=True, choices=[('1', '健康保険組合'), ('2', '協会けんぽ（全国健康保険協会）'), ('3', '各種共済組合'), ('4', '国民健康保険'), ('5', '国民健康保険組合（長けん国保）'), ('6', '後期高齢者医療制度'), ('7', '船員保険（全国健康保険協会）'), ('8', '-')], max_length=100, null=True, verbose_name='健康保険'),
        ),
        migrations.AlterField(
            model_name='soenmodel',
            name='pensionInsurance',
            field=models.CharField(blank=True, choices=[('1', '国民年金'), ('2', '厚生年金'), ('3', '-')], max_length=100, null=True, verbose_name='年金保険'),
        ),
        migrations.AlterField(
            model_name='soenmodel',
            name='retirementCooperation',
            field=models.CharField(blank=True, choices=[('1', '有'), ('2', '無'), ('3', '-')], max_length=100, null=True, verbose_name='建退協'),
        ),
        migrations.AlterField(
            model_name='specialeducationmodel',
            name='name',
            field=models.CharField(blank=True, choices=[('-', '-'), ('研削といし取替・試運転', '研削といし取替・試運転'), ('アーク溶接作業', 'アーク溶接作業'), ('フォークリフト運転業務', 'フォークリフト運転業務'), ('高所作業車の運転', '高所作業車の運転'), ('巻き上げ機の運転', '巻き上げ機の運転'), ('クレーンの運転', 'クレーンの運転'), ('移動式クレーンの運転', '移動式クレーンの運転'), ('玉掛け業務', '玉掛け業務'), ('職長教育', '職長教育'), ('職長教育（追教育）', '職長教育（追教育）'), ('安全衛生責任者', '安全衛生責任者'), ('足場組立等作業従事者特別教育', '足場組立等作業従事者特別教育'), ('有機溶剤取扱い業務', '有機溶剤取扱い業務'), ('特別教育14', '特別教育14'), ('特別教育15', '特別教育15'), ('特別教育16', '特別教育16'), ('特別教育17', '特別教育17'), ('特別教育18', '特別教育18'), ('特別教育19', '特別教育19'), ('特別教育20', '特別教育20')], max_length=30, null=True, verbose_name='特別教育'),
        ),
    ]
