# Generated by Django 4.0.1 on 2022-07-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimex', '0003_alter_soenmodel_file5_remove_soenmodel_licence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soenmodel',
            name='checking',
            field=models.BooleanField(blank=True, null=True, verbose_name='選択フラグ（ゴメン今のところ使いません⇒）'),
        ),
        migrations.AlterField(
            model_name='soenmodel',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='検索番号'),
        ),
    ]
