# Generated by Django 3.2.7 on 2021-11-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimex', '0003_auto_20211108_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soenmodel',
            name='djgroup',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属(親方内装)'),
        ),
        migrations.AlterField(
            model_name='soenmodel',
            name='djgroup2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属(souen)'),
        ),
    ]
