# Generated by Django 4.0.1 on 2022-07-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualSpot', '0007_alter_vehicle_drive_waypoint1'),
        ('reimex', '0004_alter_soenmodel_checking_alter_soenmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soenmodel',
            name='mvehicle',
            field=models.ManyToManyField(to='actualSpot.Vehicle'),
        ),
    ]
