# Generated by Django 3.2.7 on 2021-11-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualSpot', '0013_alter_vehicle_options'),
        ('reimex', '0005_auto_20211109_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='soenmodel',
            name='No_1_specific_skill_foreigner',
            field=models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '-')], max_length=100, null=True, verbose_name='一号特定技能外国人'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='carryonMachine',
            field=models.CharField(blank=True, choices=[('1', '電動ｸﾞﾗｲﾝﾀﾞｰ'), ('2', '電動ﾄﾞﾘﾙ'), ('3', 'ｺﾝﾌﾟﾚｯｻｰ'), ('4', 'アーク溶接機'), ('5', '-')], max_length=100, null=True, verbose_name='持込機械'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='constractionPermit',
            field=models.CharField(blank=True, choices=[('1', '建築工事業'), ('2', '内装仕上工事業'), ('3', '-')], max_length=100, null=True, verbose_name='建設業許可業種'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='constractionPermit_chuji',
            field=models.CharField(blank=True, choices=[('1', '大臣'), ('2', '知事'), ('3', '-')], max_length=100, null=True, verbose_name='建設業許可_大臣・知事'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='constractionPermit_gat',
            field=models.DateField(blank=True, null=True, verbose_name='建設業許可_取得年月日'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='constractionPermit_ippan',
            field=models.CharField(blank=True, choices=[('1', '特定'), ('2', '一般'), ('3', '-')], max_length=100, null=True, verbose_name='建設業許可_特定・一般'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='constractionPermit_nendo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='建設業許可_年度'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='constractionPermit_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='建設業許可_番号'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='contractDay',
            field=models.DateField(blank=True, null=True, verbose_name='工事契約日'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='contractionDetail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='工事内容'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='dangerous',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='危険物OR有機溶剤OR特定化学物質'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='finishActionDay',
            field=models.DateField(blank=True, null=True, verbose_name='請負終了工期'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='firstActionDay',
            field=models.DateField(blank=True, null=True, verbose_name='請負開始工期'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='foreignIntern',
            field=models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '-')], max_length=100, null=True, verbose_name='外国人技能実習生'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='foreignWorker',
            field=models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '-')], max_length=100, null=True, verbose_name='外国人建設就労者'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='mobileCrane',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移動式ｸﾚｰﾝ･車両系建設機械'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='mvehicle',
            field=models.ManyToManyField(to='actualSpot.Vehicle'),
        ),
        migrations.AlterField(
            model_name='soenmodel',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Link5'),
        ),
    ]
