# Generated by Django 4.0.1 on 2022-07-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimex', '0005_alter_soenmodel_mvehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soenmodel',
            name='specialEducation',
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='specialEducation',
            field=models.ManyToManyField(to='reimex.SpecialEducationModel'),
        ),
    ]
