# Generated by Django 4.0.1 on 2022-07-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimex', '0006_remove_soenmodel_specialeducation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soenmodel',
            name='licence',
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='licence',
            field=models.ManyToManyField(to='reimex.LicenceModel'),
        ),
        migrations.RemoveField(
            model_name='soenmodel',
            name='skillTraning',
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='skillTraning',
            field=models.ManyToManyField(to='reimex.SkillTraningModel'),
        ),
    ]
