# Generated by Django 3.2.7 on 2021-11-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimex', '0006_auto_20211109_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soenmodel',
            name='djgroup',
            field=models.CharField(default=' 内装', max_length=100, verbose_name='会社名(親方内装)'),
        ),
        migrations.AlterField(
            model_name='soenmodel',
            name='djgroup2',
            field=models.CharField(blank=True, default='株式会社\u3000装苑', max_length=100, null=True, verbose_name='所属(souen)'),
        ),
        migrations.AlterField(
            model_name='soenmodel',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='代表者姓名'),
        ),
    ]
