# Generated by Django 3.2.7 on 2021-11-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimex', '0007_auto_20211111_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='soenmodel',
            name='Insurance_station',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='保険＿事業所名'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='Insurance_station_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='保険＿事業所名_整理記号･番号'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='file0',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Link0'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='leadEngineer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主任技術者'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='saftyManager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='安全衛生責任者'),
        ),
        migrations.AddField(
            model_name='soenmodel',
            name='saftyPromoter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='安全衛生推進者'),
        ),
    ]
