# Generated by Django 4.0.1 on 2022-03-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checking', models.BooleanField(default=False, verbose_name='選択フラグ')),
                ('spotName', models.CharField(default='必須', max_length=50, verbose_name='現場名')),
                ('superVisor', models.CharField(default='必須', max_length=50, verbose_name='現場所長名')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='現場住所')),
                ('contractDay', models.DateField(blank=True, null=True, verbose_name='ｾﾞﾈ請負契約日')),
                ('constractionDetail', models.CharField(blank=True, max_length=50, null=True, verbose_name='ｾﾞﾈ工事内容')),
                ('firstActionDay', models.DateField(blank=True, null=True, verbose_name='全体開始工期')),
                ('finishActionDay', models.DateField(blank=True, null=True, verbose_name='全体終了工期')),
                ('firstSubcontractor', models.CharField(blank=True, max_length=50, null=True, verbose_name='上位会社')),
                ('X', models.IntegerField(default='1', verbose_name='X次')),
                ('Xx', models.IntegerField(default='2', verbose_name='Xx次')),
            ],
            options={
                'verbose_name_plural': '現場名',
            },
        ),
        migrations.CreateModel(
            name='gContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gName', models.CharField(blank=True, max_length=20, null=True, verbose_name='ｾﾞﾈｺﾝ会社名')),
                ('postalCode', models.CharField(blank=True, max_length=20, null=True, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='現住所')),
                ('telephoneNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('FaxNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax番号')),
            ],
            options={
                'verbose_name_plural': 'ｾﾞﾈｺﾝ会社',
            },
        ),
        migrations.CreateModel(
            name='mostRecent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recentName', models.CharField(default='companyName', max_length=20, verbose_name='協力会社名')),
                ('postalCode', models.CharField(blank=True, max_length=20, null=True, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='現住所')),
                ('telephoneNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('FaxNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax番号')),
                ('representative', models.CharField(blank=True, max_length=100, null=True, verbose_name='代表者名')),
                ('saftyManager', models.CharField(blank=True, max_length=100, null=True, verbose_name='安全衛生責任者')),
                ('saftyPromoter', models.CharField(blank=True, max_length=100, null=True, verbose_name='安全衛生推進者')),
                ('leadEngineer', models.CharField(blank=True, max_length=100, null=True, verbose_name='主任技術者')),
                ('file0', models.FileField(blank=True, null=True, upload_to='', verbose_name='Link0')),
                ('Insurance_station', models.CharField(blank=True, max_length=100, null=True, verbose_name='保険＿事業所名')),
                ('Insurance_station_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='保険＿事業所名_整理記号･番号')),
                ('healthInsurance', models.CharField(blank=True, choices=[('1', '健康保険組合'), ('2', '協会けんぽ（全国健康保険協会）'), ('3', '各種共済組合'), ('4', '国民健康保険'), ('5', '国民健康保険組合（長けん国保）'), ('6', '後期高齢者医療制度'), ('7', '船員保険（全国健康保険協会）'), ('8', '-')], max_length=100, null=True, verbose_name='健康保険')),
                ('file1', models.FileField(blank=True, null=True, upload_to='', verbose_name='Link1')),
                ('pensionInsurance', models.CharField(blank=True, choices=[('1', '国民年金'), ('2', '厚生年金'), ('3', '-')], max_length=100, null=True, verbose_name='年金保険')),
                ('file2', models.FileField(blank=True, null=True, upload_to='', verbose_name='Link2')),
                ('employmentinsurance', models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '適用除外'), ('4', '-')], max_length=100, null=True, verbose_name='雇用保険')),
                ('employmentinsurance_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='雇用保険番号')),
                ('file3', models.FileField(blank=True, null=True, upload_to='', verbose_name='Link3')),
                ('retirementCooperation', models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '-')], max_length=100, null=True, verbose_name='建退協')),
                ('file4', models.FileField(blank=True, null=True, upload_to='', verbose_name='Link4')),
                ('constractionPermit', models.CharField(blank=True, choices=[('1', '建築工事業'), ('2', '内装仕上工事業'), ('3', '-')], max_length=100, null=True, verbose_name='建設業許可業種')),
                ('constractionPermit_chuji', models.CharField(blank=True, choices=[('1', '大臣'), ('2', '知事'), ('3', '-')], max_length=100, null=True, verbose_name='建設業許可_大臣・知事')),
                ('constractionPermit_ippan', models.CharField(blank=True, choices=[('1', '特定'), ('2', '一般'), ('3', '-')], max_length=100, null=True, verbose_name='建設業許可_特定・一般')),
                ('constractionPermit_nendo', models.CharField(blank=True, max_length=100, null=True, verbose_name='建設業許可_年度')),
                ('constractionPermit_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='建設業許可_番号')),
                ('constractionPermit_gat', models.DateField(blank=True, null=True, verbose_name='建設業許可_取得年月日')),
                ('file5', models.FileField(blank=True, null=True, upload_to='', verbose_name='Link5')),
                ('contractDay', models.DateField(blank=True, null=True, verbose_name='工事契約日')),
                ('firstActionDay', models.DateField(blank=True, null=True, verbose_name='請負開始工期')),
                ('finishActionDay', models.DateField(blank=True, null=True, verbose_name='請負終了工期')),
                ('contractionDetail', models.CharField(blank=True, max_length=100, null=True, verbose_name='工事内容')),
                ('No_1_specific_skill_foreigner', models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '-')], max_length=100, null=True, verbose_name='一号特定技能外国人')),
                ('foreignWorker', models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '-')], max_length=100, null=True, verbose_name='外国人建設就労者')),
                ('foreignIntern', models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '-')], max_length=100, null=True, verbose_name='外国人技能実習生')),
                ('carryonMachine', models.CharField(blank=True, choices=[('1', '電動ｸﾞﾗｲﾝﾀﾞｰ'), ('2', '電動ﾄﾞﾘﾙ'), ('3', 'ｺﾝﾌﾟﾚｯｻｰ'), ('4', 'アーク溶接機'), ('5', '-')], max_length=100, null=True, verbose_name='持込機械')),
                ('mobileCrane', models.CharField(blank=True, max_length=100, null=True, verbose_name='移動式ｸﾚｰﾝ･車両系建設機械')),
                ('dangerous', models.CharField(blank=True, max_length=100, null=True, verbose_name='危険物OR有機溶剤OR特定化学物質')),
            ],
            options={
                'verbose_name_plural': '協力会社',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrecent', models.CharField(blank=True, max_length=20, null=True, verbose_name='所属')),
                ('vehicleNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='車両番号')),
                ('firstUse', models.DateField(blank=True, null=True, verbose_name='使用期間開始')),
                ('finishUse', models.DateField(blank=True, null=True, verbose_name='使用期間終了')),
                ('vehicleModel', models.CharField(blank=True, max_length=20, null=True, verbose_name='車検証_型式')),
                ('firstInspection', models.DateField(blank=True, null=True, verbose_name='車検証_車検期間開始')),
                ('finishInspection', models.DateField(blank=True, null=True, verbose_name='車検証_車検期間終了')),
                ('file1', models.FileField(blank=True, null=True, upload_to='', verbose_name='Link1車検証')),
                ('liabilityComp', models.CharField(blank=True, max_length=20, null=True, verbose_name='自賠責_保険会社')),
                ('liability_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='自賠責_証券番号')),
                ('firstliability', models.DateField(blank=True, null=True, verbose_name='自賠責_保険期間開始')),
                ('finishliability', models.DateField(blank=True, null=True, verbose_name='自賠責_保険期間終了')),
                ('file2', models.FileField(blank=True, null=True, upload_to='', verbose_name='Link2自賠責')),
                ('voluntaryInsureComp', models.CharField(blank=True, max_length=20, null=True, verbose_name='任意保険_保険会社')),
                ('voluntaryInsureNum', models.CharField(blank=True, max_length=20, null=True, verbose_name='任意保険_証券番号')),
                ('firstVoluntary', models.DateField(blank=True, null=True, verbose_name='任意保険_保険期間開始')),
                ('finishVoluntary', models.DateField(blank=True, null=True, verbose_name='任意保険_保険期間終了')),
                ('voluntary_object', models.CharField(blank=True, max_length=20, null=True, verbose_name='任意保険_対物_千円')),
                ('voluntary_human', models.CharField(blank=True, max_length=20, null=True, verbose_name='任意保険_対人_千円')),
                ('voluntary_passenger', models.CharField(blank=True, max_length=20, null=True, verbose_name='任意保険_搭乗者_千円')),
                ('file3', models.FileField(blank=True, null=True, upload_to='', verbose_name='Link3任意保険')),
                ('drive_departure', models.CharField(blank=True, max_length=100, null=True, verbose_name='運転_出発地')),
                ('drive_waypoint1', models.CharField(blank=True, max_length=100, null=True, verbose_name='運転_経由１')),
                ('drive_waypoint2', models.CharField(blank=True, max_length=100, null=True, verbose_name='運転_経由2')),
                ('drive_arrival', models.CharField(blank=True, max_length=100, null=True, verbose_name='運転_到着地')),
            ],
            options={
                'verbose_name_plural': '車両',
            },
        ),
    ]
