# Generated by Django 3.2.7 on 2021-11-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualSpot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gName', models.CharField(blank=True, max_length=20, null=True, verbose_name='ｾﾞﾈｺﾝ会社名')),
                ('postalCode', models.CharField(blank=True, max_length=20, null=True, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='現住所')),
                ('telephoneNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
            ],
            options={
                'verbose_name_plural': 'ｾﾞﾈｺﾝ会社',
            },
        ),
        migrations.AlterModelOptions(
            name='mostrecent',
            options={'verbose_name_plural': '直近会社'},
        ),
        migrations.RemoveField(
            model_name='aspot',
            name='kanaName',
        ),
        migrations.RemoveField(
            model_name='aspot',
            name='mostRecent',
        ),
        migrations.RemoveField(
            model_name='aspot',
            name='XSubcontractor',
        ),
        migrations.AddField(
            model_name='aspot',
            name='XSubcontractor',
            field=models.ManyToManyField(to='actualSpot.mostRecent'),
        ),
        migrations.AlterField(
            model_name='mostrecent',
            name='recentName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='直近会社名'),
        ),
        migrations.AddField(
            model_name='aspot',
            name='gContractor',
            field=models.ManyToManyField(to='actualSpot.gContractor'),
        ),
    ]
