# Generated by Django 3.2.7 on 2021-11-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualSpot', '0002_auto_20211105_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcontractor',
            options={'verbose_name_plural': 'ｾﾞﾈｺﾝ会社or直近上位会社'},
        ),
        migrations.AlterModelOptions(
            name='mostrecent',
            options={'verbose_name_plural': '協力会社'},
        ),
        migrations.AlterField(
            model_name='gcontractor',
            name='gName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ｾﾞﾈｺﾝ会社名or直近上位会社'),
        ),
        migrations.AlterField(
            model_name='mostrecent',
            name='recentName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='協力会社名'),
        ),
    ]
