# Generated by Django 3.2.7 on 2021-11-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualSpot', '0003_auto_20211108_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspot',
            name='X',
            field=models.IntegerField(default='協力会社', verbose_name='X次'),
        ),
        migrations.AlterField(
            model_name='aspot',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='aspot',
            name='firstSubcontractor',
            field=models.CharField(default='株式会社\u3000装苑', max_length=50, verbose_name='現在 装苑 として'),
        ),
    ]
