# Generated by Django 4.0.1 on 2022-05-21 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimex', '0002_alter_soenmodel_licence_alter_soenmodel_mvehicle_and_more'),
        ('actualSpot', '0003_alter_aspot_xsubcontractor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspot',
            name='XSubcontractor',
        ),
        migrations.AddField(
            model_name='aspot',
            name='XSubcontractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='actualSpot.mostrecent'),
        ),
        migrations.RemoveField(
            model_name='aspot',
            name='XxSubcontractor',
        ),
        migrations.AddField(
            model_name='aspot',
            name='XxSubcontractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reimex.soenmodel'),
        ),
        migrations.RemoveField(
            model_name='aspot',
            name='gContractor',
        ),
        migrations.AddField(
            model_name='aspot',
            name='gContractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='actualSpot.gcontractor'),
        ),
    ]
