# Generated by Django 4.0.1 on 2022-05-21 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actualSpot', '0004_remove_aspot_xsubcontractor_aspot_xsubcontractor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspot',
            name='gContractor',
            field=models.ForeignKey(blank=True, default='必須', null=True, on_delete=django.db.models.deletion.PROTECT, to='actualSpot.gcontractor'),
        ),
    ]
