# Generated by Django 3.2.7 on 2021-11-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualSpot', '0005_auto_20211109_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspot',
            name='firstSubcontractor',
        ),
        migrations.RemoveField(
            model_name='mostrecent',
            name='Xx',
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='FaxNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax番号'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='Insurance_station',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='保険＿事業所名'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='Insurance_station_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='保険＿事業所名_整理記号･番号'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='No_1_specific_skill_foreigner',
            field=models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '-')], max_length=100, null=True, verbose_name='一号特定技能外国人'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='constractionPermit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='建設業許可'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='contractDay',
            field=models.DateField(blank=True, null=True, verbose_name='契約日'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='contractionDetail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='工事内容'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='employmentinsurance',
            field=models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '適用除外'), ('4', '-')], max_length=100, null=True, verbose_name='雇用保険'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='employmentinsurance_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='雇用保険番号'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='file0',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Link0'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Link1'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Link2'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Link3'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Link4'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Link5'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='finishActionDay',
            field=models.DateField(blank=True, null=True, verbose_name='全体終了工期'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='firstActionDay',
            field=models.DateField(blank=True, null=True, verbose_name='全体開始工期'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='foreignIntern',
            field=models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '-')], max_length=100, null=True, verbose_name='外国人技能実習生'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='foreignWorker',
            field=models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '-')], max_length=100, null=True, verbose_name='外国人建設就労者'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='healthInsurance',
            field=models.CharField(blank=True, choices=[('1', '健康保険組合'), ('2', '協会けんぽ（全国健康保険協会）'), ('3', '各種共済組合'), ('4', '国民健康保険'), ('5', '国民健康保険組合（長けん国保）'), ('6', '後期高齢者医療制度'), ('7', '船員保険（全国健康保険協会）'), ('8', '-')], max_length=100, null=True, verbose_name='健康保険'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='leadEngineer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主任技術者'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='pensionInsurance',
            field=models.CharField(blank=True, choices=[('1', '国民年金'), ('2', '厚生年金'), ('3', '-')], max_length=100, null=True, verbose_name='年金保険'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='representative',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='代表者名'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='retirementCooperation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='建退協'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='saftyManager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='安全衛生責任者'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='saftyPromoter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='安全衛生推進者'),
        ),
        migrations.AlterField(
            model_name='aspot',
            name='X',
            field=models.IntegerField(default='1', verbose_name='X次'),
        ),
        migrations.AlterField(
            model_name='mostrecent',
            name='recentName',
            field=models.CharField(default='companyName', max_length=20, verbose_name='協力会社名'),
        ),
    ]
