# Generated by Django 4.0.1 on 2022-05-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualSpot', '0005_alter_aspot_gcontractor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspot',
            name='gContractor',
        ),
        migrations.AddField(
            model_name='aspot',
            name='gContractor',
            field=models.ManyToManyField(blank=True, default='必須', null=True, to='actualSpot.gContractor'),
        ),
    ]
