# Generated by Django 4.0.1 on 2022-07-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualSpot', '0006_remove_aspot_gcontractor_aspot_gcontractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='drive_waypoint1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='運転_経由1'),
        ),
    ]
