# Generated by Django 3.2.7 on 2021-11-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimex', '0003_auto_20211108_1735'),
        ('actualSpot', '0006_auto_20211109_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aspot',
            old_name='members',
            new_name='XxSubcontractor',
        ),
        migrations.AddField(
            model_name='aspot',
            name='Xx',
            field=models.IntegerField(default='2', verbose_name='X次'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='members',
            field=models.ManyToManyField(to='reimex.SoenModel'),
        ),
        migrations.AlterField(
            model_name='mostrecent',
            name='contractDay',
            field=models.DateField(blank=True, null=True, verbose_name='工事契約日'),
        ),
        migrations.AlterField(
            model_name='mostrecent',
            name='finishActionDay',
            field=models.DateField(blank=True, null=True, verbose_name='請負終了工期'),
        ),
        migrations.AlterField(
            model_name='mostrecent',
            name='firstActionDay',
            field=models.DateField(blank=True, null=True, verbose_name='請負開始工期'),
        ),
        migrations.AlterField(
            model_name='mostrecent',
            name='retirementCooperation',
            field=models.CharField(blank=True, choices=[('1', '無'), ('2', '有'), ('3', '-')], max_length=100, null=True, verbose_name='建退協'),
        ),
    ]
