# Generated by Django 4.0.1 on 2022-07-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualSpot', '0007_alter_vehicle_drive_waypoint1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspot',
            name='gContractor',
            field=models.ManyToManyField(to='actualSpot.gContractor'),
        ),
    ]
