# Generated by Django 3.2.7 on 2021-11-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualSpot', '0007_auto_20211109_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspot',
            name='firstSubcontractor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='上位会社'),
        ),
        migrations.AlterField(
            model_name='aspot',
            name='Xx',
            field=models.IntegerField(default='2', verbose_name='Xx次'),
        ),
    ]
