# Generated by Django 3.2.7 on 2021-11-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualSpot', '0008_auto_20211109_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostrecent',
            name='constractionPermit_chuji',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='建設業許可_大臣・知事'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='constractionPermit_gat',
            field=models.DateField(blank=True, null=True, verbose_name='建設業許可_取得年月日'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='constractionPermit_ippan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='建設業許可_特定・一般'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='constractionPermit_nendo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='建設業許可_年度'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='constractionPermit_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='建設業許可_番号'),
        ),
        migrations.AlterField(
            model_name='mostrecent',
            name='constractionPermit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='建設業許可業種'),
        ),
    ]
