# Generated by Django 3.2.7 on 2021-11-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimex', '0005_auto_20211109_1349'),
        ('actualSpot', '0010_auto_20211109_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostrecent',
            name='carryonMachine',
            field=models.CharField(blank=True, choices=[('1', '電動ｸﾞﾗｲﾝﾀﾞｰ'), ('2', '電動ﾄﾞﾘﾙ'), ('3', 'ｺﾝﾌﾟﾚｯｻｰ'), ('4', 'アーク溶接機'), ('5', '-')], max_length=100, null=True, verbose_name='持込機械'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='dangerous',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='危険物OR有機溶剤OR特定化学物質'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='mobileCrane',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='移動式ｸﾚｰﾝ･車両系建設機械'),
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='車両'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrecent', models.CharField(blank=True, max_length=20, null=True, verbose_name='所属')),
                ('vehicleNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='車両番号')),
                ('firstUse', models.DateField(blank=True, null=True, verbose_name='使用期間開始')),
                ('finishUse', models.DateField(blank=True, null=True, verbose_name='使用期間終了')),
                ('vehicleModel', models.CharField(blank=True, max_length=20, null=True, verbose_name='車検証_型式')),
                ('firstInspection', models.DateField(blank=True, null=True, verbose_name='車検証_車検期間開始')),
                ('finishInspection', models.DateField(blank=True, null=True, verbose_name='車検証_車検期間終了')),
                ('file1', models.FileField(blank=True, null=True, upload_to='', verbose_name='Link1車検証')),
                ('liabilityComp', models.CharField(blank=True, max_length=20, null=True, verbose_name='自賠責_保険会社')),
                ('liability_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='自賠責_証券番号')),
                ('firstliability', models.DateField(blank=True, null=True, verbose_name='自賠責_保険期間開始')),
                ('finishliability', models.DateField(blank=True, null=True, verbose_name='自賠責_保険期間終了')),
                ('file2', models.FileField(blank=True, null=True, upload_to='', verbose_name='Link2自賠責')),
                ('voluntaryInsureComp', models.CharField(blank=True, max_length=20, null=True, verbose_name='任意保険_保険会社')),
                ('voluntaryInsureNum', models.CharField(blank=True, max_length=20, null=True, verbose_name='任意保険_証券番号')),
                ('firstVoluntary', models.DateField(blank=True, null=True, verbose_name='任意保険_保険期間開始')),
                ('finishVoluntary', models.DateField(blank=True, null=True, verbose_name='任意保険_保険期間終了')),
                ('voluntary_object', models.CharField(blank=True, max_length=20, null=True, verbose_name='任意保険_対物_千円')),
                ('voluntary_human', models.CharField(blank=True, max_length=20, null=True, verbose_name='任意保険_対人_千円')),
                ('voluntary_passenger', models.CharField(blank=True, max_length=20, null=True, verbose_name='任意保険_搭乗者_千円')),
                ('file3', models.FileField(blank=True, null=True, upload_to='', verbose_name='Link3任意保険')),
                ('drive_departure', models.CharField(blank=True, max_length=100, null=True, verbose_name='運転_出発地')),
                ('drive_waipoint1', models.CharField(blank=True, max_length=100, null=True, verbose_name='運転_経由１')),
                ('drive_waypoint2', models.CharField(blank=True, max_length=100, null=True, verbose_name='運転_経由2')),
                ('drive_arrival', models.CharField(blank=True, max_length=100, null=True, verbose_name='運転_到着地')),
                ('driver', models.ManyToManyField(to='reimex.SoenModel')),
            ],
        ),
    ]
