# Generated by Django 3.2.7 on 2021-11-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualSpot', '0011_auto_20211109_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='mostrecent',
            new_name='mrecent',
        ),
        migrations.RemoveField(
            model_name='mostrecent',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='mostrecent',
            name='vehicle',
            field=models.ManyToManyField(to='actualSpot.Vehicle'),
        ),
    ]
