# Generated by Django 3.2.7 on 2021-11-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualSpot', '0012_auto_20211109_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name_plural': '車両'},
        ),
    ]
