# Generated by Django 3.2.7 on 2021-11-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualSpot', '0013_alter_vehicle_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='drive_waipoint1',
            new_name='drive_waypoint1',
        ),
    ]
