# Generated by Django 3.2.7 on 2021-11-11 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actualSpot', '0014_rename_drive_waipoint1_vehicle_drive_waypoint1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspot',
            name='XSubcontractor',
        ),
        migrations.AddField(
            model_name='aspot',
            name='XSubcontractor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='actualSpot.mostrecent'),
        ),
    ]
