# Generated by Django 3.2.7 on 2021-11-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimex', '0006_auto_20211109_1636'),
        ('actualSpot', '0015_auto_20211111_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspot',
            name='XxSubcontractor',
            field=models.ManyToManyField(blank=True, null=True, to='reimex.SoenModel'),
        ),
    ]
