# Generated by Django 3.2.7 on 2021-11-11 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimex', '0006_auto_20211109_1636'),
        ('actualSpot', '0016_alter_aspot_xxsubcontractor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspot',
            name='XxSubcontractor',
        ),
        migrations.AddField(
            model_name='aspot',
            name='XxSubcontractor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reimex.soenmodel'),
        ),
    ]
