# Generated by Django 3.2.7 on 2021-11-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimex', '0006_auto_20211109_1636'),
        ('actualSpot', '0017_auto_20211111_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspot',
            name='XSubcontractor',
        ),
        migrations.AddField(
            model_name='aspot',
            name='XSubcontractor',
            field=models.ManyToManyField(to='actualSpot.mostRecent'),
        ),
        migrations.RemoveField(
            model_name='aspot',
            name='XxSubcontractor',
        ),
        migrations.AddField(
            model_name='aspot',
            name='XxSubcontractor',
            field=models.ManyToManyField(to='reimex.SoenModel'),
        ),
    ]
