# Generated by Django 4.0.1 on 2022-07-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='steelPartsM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstDay', models.DateField(help_text='2022-12-21', verbose_name='摘要期日~')),
                ('SM', models.IntegerField(help_text='5m定尺', verbose_name='ｼﾝｸﾞﾙﾊﾞｰ')),
                ('WM', models.IntegerField(verbose_name='ﾀﾞﾌﾞﾙﾊﾞｰ')),
                ('CC', models.IntegerField(verbose_name='Cチャン')),
            ],
        ),
    ]
