# Generated by Django 4.0.1 on 2022-07-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Number', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wagesM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceiling300', models.IntegerField(verbose_name='軽鉄天井下地組')),
                ('wall50', models.IntegerField(verbose_name='軽鉄壁下地W50')),
                ('wall65', models.IntegerField(verbose_name='軽鉄壁下地W65')),
                ('wall75', models.IntegerField(verbose_name='軽鉄壁下地W75')),
                ('wall90', models.IntegerField(verbose_name='軽鉄壁下地W90')),
                ('wall100', models.IntegerField(verbose_name='軽鉄壁下地W100')),
            ],
        ),
        migrations.AlterField(
            model_name='steelpartsm',
            name='firstDay',
            field=models.DateField(help_text='[例］2022-12-21\u3000⇐日付は「-」(ﾊｲﾌﾝ)で繋げてください', verbose_name='摘要期日~'),
        ),
    ]
