# Generated by Django 4.0.1 on 2022-02-17 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydjangoSoen', '0004_alter_iddetail_idmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iddetail',
            name='IdModel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mydjangoSoen.idmodel'),
        ),
    ]
