# Generated by Django 4.0.1 on 2022-02-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ﾀｲﾄﾙ')),
                ('text', models.TextField(verbose_name='ﾃｷｽﾄ')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('update_at', models.DateField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': 'ブログ',
                'verbose_name_plural': 'ブログう',
            },
        ),
    ]
