# Generated by Django 4.0.1 on 2022-02-10 05:57

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('m3ch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=markdownx.models.MarkdownxField(verbose_name='ﾃｷｽﾄ'),
        ),
    ]
