# Generated by Django 4.0.1 on 2022-02-14 02:54

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('m3ch', '0002_alter_blog_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=markdownx.models.MarkdownxField(help_text='ﾏｰｸﾀﾞｳﾝ形式で書いてください', verbose_name='ﾃｷｽﾄ'),
        ),
    ]
