# Generated by Django 4.0.1 on 2022-02-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3ch', '0003_alter_blog_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ﾀｲﾄﾙ')),
                ('text', models.TextField(blank=True, null=True, verbose_name='ﾃｷｽﾄ')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': 'ブログ',
                'verbose_name_plural': 'プログ',
            },
        ),
    ]
