# Generated by Django 4.0.1 on 2022-02-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m3ch', '0004_imageblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'ブログ', 'verbose_name_plural': 'ブログ'},
        ),
        migrations.AlterModelOptions(
            name='imageblog',
            options={'verbose_name': 'mIMブログ', 'verbose_name_plural': 'mimプログ'},
        ),
    ]
