# Generated by Django 4.0.1 on 2022-03-18 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m3ch', '0005_alter_blog_options_alter_imageblog_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='text',
        ),
    ]
