# Generated by Django 4.0.1 on 2022-04-07 07:24

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('m3ch', '0006_remove_blog_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageBlog',
        ),
        migrations.AddField(
            model_name='blog',
            name='text',
            field=markdownx.models.MarkdownxField(default='', help_text='ﾏｰｸﾀﾞｳﾝ形式で書いてください', verbose_name='ﾃｷｽﾄ'),
        ),
    ]
