# Generated by Django 4.0.1 on 2022-04-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3ch', '0007_delete_imageblog_blog_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.CharField(default='', max_length=50, verbose_name='ﾃｷｽﾄ'),
        ),
    ]
