# Generated by Django 4.0.1 on 2022-03-18 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new_name', max_length=20, verbose_name='名前')),
                ('add', models.CharField(blank=True, default='sasebo', max_length=60, null=True, verbose_name='住所')),
                ('tel', models.CharField(blank=True, default='0956-', max_length=15, null=True, verbose_name='電話番号')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberDetailMo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodtype', models.CharField(blank=True, default='A', max_length=10, null=True, verbose_name='血液型')),
                ('age', models.IntegerField(blank=True, default='0', null=True, verbose_name='年齢')),
                ('memberm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='Soen.membermo')),
            ],
        ),
        migrations.CreateModel(
            name='BlogMo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='title', max_length=50, null=True, verbose_name='ﾀｲﾄﾙ')),
                ('text', models.TextField(blank=True, default='text', null=True, verbose_name='ﾃｷｽﾄ & ﾌｫﾄ')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('memberm2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='Soen.membermo')),
            ],
            options={
                'verbose_name': 'ブログ',
                'verbose_name_plural': 'sプログ',
            },
        ),
    ]
