# Generated by Django 4.0.1 on 2022-02-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogm',
            name='text',
            field=models.TextField(blank=True, default='text', null=True, verbose_name='ﾃｷｽﾄ & ﾌｫﾄ'),
        ),
        migrations.AlterField(
            model_name='blogm',
            name='title',
            field=models.CharField(blank=True, default='title', max_length=50, null=True, verbose_name='ﾀｲﾄﾙ'),
        ),
        migrations.AlterField(
            model_name='memberdetailm',
            name='age',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='memberdetailm',
            name='bloodtype',
            field=models.CharField(blank=True, default='A', max_length=10, null=True, verbose_name='血液型'),
        ),
    ]
