# Generated by Django 4.0.1 on 2022-04-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmo',
            name='text',
            field=models.TextField(blank=True, default='text', null=True, verbose_name='ﾃｷｽﾄ'),
        ),
    ]
